
// https://www.kingston.com/datasheets/SDCIT-specsheet-8gb-32gb_jp.pdf
// https://so-zou.jp/robot/tech/microcomputer/pic/example/sd-card/
// https://www.microchip.com/forums/m530149.aspx
// https://www.convict.lu/pdf/ProdManualSDCardv1.9.pdf
// https://advdownload.advantech.com/productfile/PIS/96FMMSDI-8G-ET-AT1/Product%20-%20Datasheet/96FMMSDI-8G-ET-AT1_datasheet20170331165830.pdf
// http://users.ece.utexas.edu/~valvano/EE345M/SD_Physical_Layer_Spec.pdf
// http://yourcmc.ru/wiki/images/5/55/EMMC_JESD84-A441.pdf

#define STATUS_OUT_OF_RANGE			(1 << 31)
#define STATUS_ADDRESS_ERROR		(1 << 30)
#define STATUS_BLOCK_LEN_ERROR		(1 << 29)
#define STATUS_ERASE_SEQ_ERROR		(1 << 28)
#define STATUS_ERASE_PARAM_ERROR	(1 << 27)
#define STATUS_WP_VIOLATION			(1 << 26)
#define STATUS_CARD_IS_LOCKED		(1 << 25)
#define STATUS_LOCK_UNLOCK_FAIL		(1 << 24)
#define STATUS_COM_ECC_ERROR		(1 << 23)
#define STATUS_ILLEGAL_COMMAND		(1 << 22)
#define STATUS_CARD_ECC_FAILED		(1 << 21)
#define STATUS_CC_ERROR				(1 << 20)
#define STATUS_ERROR				(1 << 19)
#define STATUS_CSD_OVERWRITE		(1 << 16)
#define STATUS_WP_ERASE_SKIP		(1 << 15)
#define STATUS_CARD_ECC_DISABLED	(1 << 14)
#define STATUS_ERASE_RESET			(1 << 13)
#define STATUS_CURRENT_STATE_SHIFT	9
#define STATUS_CURRENT_STATE_MASK	(0xF << STATUS_CURRENT_STATE_SHIFT)
#define STATUS_READY_FOR_DATA		(1 << 8)
#define STATUS_FX_EVENT				(1 << 6)
#define STATUS_APP_CMD				(1 << 5)
#define STATUS_AKE_SEQ_ERROR		(1 << 3)

#define SPIR1_IN_IDLE_STATE			(1 << 0)
#define SPIR1_ERASE_RESET			(1 << 1)
#define SPIR1_ILLEGAL_CMD			(1 << 2)
#define SPIR1_CRC_ERR				(1 << 3)
#define SPIR1_ERASE_SEQ_ERR			(1 << 4)
#define SPIR1_ADDRESS_ERR			(1 << 5)
#define SPIR1_PARAM_ERR				(1 << 6)

#define SPIR2_CARD_IS_LOCKED		(1 << 0)
#define SPIR2_WP_ERASE_SKIP_LK_FAIL	(1 << 1)
#define SPIR2_ERROR					(1 << 2)
#define SPIR2_CC_ERROR				(1 << 3)
#define SPIR2_CARD_ECC_FAIL			(1 << 4)
#define SPIR2_WP_VIOLATION			(1 << 5)
#define SPIR2_ERASE_PARAM			(1 << 6)
#define SPIR2_OUTRANGE_CSD_OVERWRITE	(1 << 7)

#define MMC_GO_IDLE_STATE			0	// CMD0
#define MMC_SEND_OP_COND			1	// CMD1
#define MMC_SWITCH_FUNC				6	// CMD6
#define MMC_SEND_EXT_CSD			8	// CMD8
#define MMC_SEND_CSD				9	// CMD9
#define MMC_SEND_CID				10	// CMD10
#define MMC_STOP_TRANSMISSION		12	// CMD12
#define MMC_SEND_STATUS				13	// CMD13
#define MMC_BUSTEST_R				14	// CMD14
#define MMC_SET_BLOCKLEN			16	// CMD16
#define MMC_READ_SINGLE_BLOCK		17	// CMD17
#define MMC_READ_MULTIPLE_BLOCK		18	// CMD18
#define MMC_BUSTEST_W				19	// CMD19
#define MMC_WRITE_BLOCK				24	// CMD24
#define MMC_WRITE_MULTIPLE_BLOCK	25	// CMD25
#define MMC_PROGRAM_CSD				27	// CMD27
#define MMC_SET_WRITE_PROT			28	// CMD28
#define MMC_CLR_WRITE_PROT			29	// CMD29
#define MMC_SEND_WRITE_PROT			30	// CMD30
#define MMC_ERASE_WR_BLK_START_ADDR	32	// CMD32
#define MMC_ERASE_WR_BLK_END_ADDR	33	// CMD33
#define MMC_ERASE					38	// CMD38
#define MMC_FAST_IO					39	// CMD39
#define MMC_INTERRUPT_REQUEST		40	// CMD40
#define MMC_LOCK_UNLOCK				42	// CMD42
#define MMC_APP_CMD					55	// CMD55
#define MMC_GEN_CMD					56	// CMD56
#define MMC_READ_OCR				58	// CMD58
#define MMC_CRC_ON_OFF				59	// CMD59
#define MMC_SET_BUS_WIDTH			6	// ACMD6
#define MMC_SD_STATUS				13	// ACMD13
#define MMC_SEND_NUM_WR_BLOCKS		22	// ACMD22
#define MMC_SET_WR_BLK_ERASE_COUNT	23	// ACMD23
#define MMC_SD_APP_OP_COND			41	// ACMD41
#define MMC_SET_CLR_CARD_DETECT		42	// ACMD42
#define MMC_SEND_SCR				51	// ACMD51
#define MMC_SECURE_READ_MULTI_BLOCK	18	// ACMD18
#define MMC_SECURE_WRITE_MULTI_BLOCK	25	// ACMD25
#define MMC_SECURE_WRITE_MKB		26	// ACMD26
#define MMC_SECURE_ERASE			38	// ACMD38
#define MMC_GET_MKB					43	// ACMD43
#define MMC_GET_MID					44	// ACMD44
#define MMC_SET_CER_RN1				45	// ACMD45
#define MMC_SET_CER_RN2				46	// ACMD46
#define MMC_SET_CER_RES2			47	// ACMD47
#define MMC_SET_CER_RES1			48	// ACMD48
#define MMC_CHANGE_SECURE_AREA		49	// ACMD49

#define MMC_GO_IDLE_STATE			0	// SD:CMD0
#define MMC_ALL_SEND_CID			2	// SD:CMD2
#define MMC_SET_RELATIVE_ADDR		3	// SD:CMD3
#define MMC_SET_DSR					4	// SD:CMD4
#define MMC_SWITCH_FUNC				6	// SD:CMD6
#define MMC_SELECT_CARD				7	// SD:CMD7
#define MMC_SEND_IF_COND			8	// SD:CMD8
#define MMC_SEND_CSD				9	// SD:CMD9
#define MMC_SEND_CID				10	// SD:CMD10
#define MMC_READ_DAT_UNTIL_STOP		11	// SD:CMD11
#define MMC_STOP_TRANSMISSION		12	// SD:CMD12
#define MMC_SEND_STATUS				13	// SD:CMD13
#define MMC_GO_INACTIVE_STATE		15	// SD:CMD15
#define MMC_SET_BLOCKLEN			16	// SD:CMD16
#define MMC_READ_SINGLE_BLOCK		17	// SD:CMD17
#define MMC_READ_MULTIPLE_BLOCK		18	// SD:CMD18
#define MMC_WRITE_DAT_UNTIL_STOP	20	// SD:CMD20
#define MMC_SET_BLOCK_COUNT			23	// SD:CMD23
#define MMC_WRITE_BLOCK				24	// SD:CMD24
#define MMC_WRITE_MULTIPLE_BLOCK	25	// SD:CMD25
#define MMC_PROGRAM_CID				26	// SD:CMD26
#define MMC_PROGRAM_CSD				27	// SD:CMD27
#define MMC_SET_WRITE_PROT			28	// SD:CMD28
#define MMC_CLR_WRITE_PROT			29	// SD:CMD29
#define MMC_SEND_WRITE_PROT			30	// SD:CMD30
#define MMC_ERASE_WR_BLK_START		32	// SD:CMD32
#define MMC_ERASE_WR_BLK_END		33	// SD:CMD33
#define MMC_UNTAG_SECTOR_			34	// SD:CMD35
#define MMC_TAG_ERASE_GROUP_START	35	// SD:CMD35
#define MMC_TAG_ERASE_GROUP_END		36	// SD:CMD36
#define MMC_ERASE					38	// SD:CMD38
#define MMC_LOCK_UNLOCK				42	// SD:CMD42
#define MMC_APP_CMD					55	// SD:CMD55
#define MMC_GEN_CMD					56	// SD:CMD56
#define MMC_SET_BUS_WIDTH			6	// SD:ACMD6
#define MMC_SD_STATUS				13	// SD:ACMD13
#define MMC_SEND_NUM_WR_BLOCKS		22	// SD:ACMD22
#define MMC_SET_WR_BLK_ERASE_COUNT	23	// SD:ACMD23
#define MMC_SD_APP_OP_COND			41	// SD:ACMD41
#define MMC_SET_CLR_CARD_DETECT		42	// SD:ACMD42
#define MMC_SEND_SCR				51	// SD:ACMD51
#define MMC_SECURE_READ_MULTI_BLOCK	18	// SD:ACMD18
#define MMC_SECURE_WRITE_MULTI_BLOCK	25	// SD:ACMD25
#define MMC_SECURE_WRITE_MKB		26	// SD:ACMD26
#define MMC_SECURE_ERASE			38	// SD:ACMD38
#define MMC_GET_MKB					43	// SD:ACMD43
#define MMC_GET_MID					44	// SD:ACMD44
#define MMC_SET_CER_RN1				45	// SD:ACMD45
#define MMC_SET_CER_RN2				46	// SD:ACMD46
#define MMC_SET_CER_RES2			47	// SD:ACMD47
#define MMC_SET_CER_RES1			48	// SD:ACMD48
#define MMC_CHANGE_SECURE_AREA		49	// SD:ACMD49

#define OCR_NOTBUSY					(1 << 31)
#define OCR_CCS						(1 << 30)
#define OCR_VOLT_MSK				(0x1FF << 15)

#define CCC_BASIC					(1 << 0)
#define CCC_STREAM_READ				(1 << 1)
#define CCC_BLOCK_READ				(1 << 2)
#define CCC_STREAM_WRITE			(1 << 3)
#define CCC_BLOCK_WRITE				(1 << 4)
#define CCC_ERASE					(1 << 5)
#define CCC_WRITE_PROT				(1 << 6)
#define CCC_LOCK_CARD				(1 << 7)
#define CCC_APP_SPEC				(1 << 8)
#define CCC_IO_MODE					(1 << 9)
#define CCC_SWITCH					(1 << 10)

#define CSD_SPEC_VER_3				3

#define SD_APP_GO_IDLE_STATE			0	// SD:CMD0
#define SD_APP_ALL_SEND_CID				2	// SD:CMD2
#define SD_APP_SET_RELATIVE_ADDR		3	// SD:CMD3
#define SD_APP_SET_DSR					4	// SD:CMD4
#define SD_APP_SWITCH_FUNC				6	// SD:CMD6
#define SD_APP_SELECT_CARD				7	// SD:CMD7
#define SD_APP_SEND_IF_COND				8	// SD:CMD8
#define SD_APP_SEND_CSD					9	// SD:CMD9
#define SD_APP_SEND_CID					10	// SD:CMD10
#define SD_APP_READ_DAT_UNTIL_STOP		11	// SD:CMD11
#define SD_APP_STOP_TRANSMISSION		12	// SD:CMD12
#define SD_APP_SEND_STATUS				13	// SD:CMD13
#define SD_APP_GO_INACTIVE_STATE		15	// SD:CMD15
#define SD_APP_SET_BLOCKLEN				16	// SD:CMD16
#define SD_APP_READ_SINGLE_BLOCK		17	// SD:CMD17
#define SD_APP_READ_MULTIPLE_BLOCK		18	// SD:CMD18
#define SD_APP_WRITE_DAT_UNTIL_STOP		20	// SD:CMD20
#define SD_APP_SET_BLOCK_COUNT			23	// SD:CMD23
#define SD_APP_WRITE_BLOCK				24	// SD:CMD24
#define SD_APP_WRITE_MULTIPLE_BLOCK		25	// SD:CMD25
#define SD_APP_PROGRAM_CID				26	// SD:CMD26
#define SD_APP_PROGRAM_CSD				27	// SD:CMD27
#define SD_APP_SET_WRITE_PROT			28	// SD:CMD28
#define SD_APP_CLR_WRITE_PROT			29	// SD:CMD29
#define SD_APP_SEND_WRITE_PROT			30	// SD:CMD30
#define SD_APP_ERASE_WR_BLK_START		32	// SD:CMD32
#define SD_APP_ERASE_WR_BLK_END			33	// SD:CMD33
#define SD_APP_UNTAG_SECTOR_			34	// SD:CMD35
#define SD_APP_TAG_ERASE_GROUP_START	35	// SD:CMD35
#define SD_APP_TAG_ERASE_GROUP_END		36	// SD:CMD36
#define SD_APP_ERASE					38	// SD:CMD38
#define SD_APP_LOCK_UNLOCK				42	// SD:CMD42
#define SD_APP_APP_CMD					55	// SD:CMD55
#define SD_APP_GEN_CMD					56	// SD:CMD56
#define SD_APP_SET_BUS_WIDTH			6	// SD:ACMD6
#define SD_APP_SD_STATUS				13	// SD:ACMD13
#define SD_APP_SEND_NUM_WR_BLOCKS		22	// SD:ACMD22
#define SD_APP_SET_WR_BLK_ERASE_COUNT	23	// SD:ACMD23
#define SD_APP_SD_APP_OP_COND			41	// SD:ACMD41
#define SD_APP_SET_CLR_CARD_DETECT		42	// SD:ACMD42
#define SD_APP_SEND_SCR					51	// SD:ACMD51
#define SD_APP_SECURE_READ_MULTI_BLOCK	18	// SD:ACMD18
#define SD_APP_SECURE_WRITE_MULTI_BLOCK	25	// SD:ACMD25
#define SD_APP_SECURE_WRITE_MKB			26	// SD:ACMD26
#define SD_APP_SECURE_ERASE				38	// SD:ACMD38
#define SD_APP_GET_MKB					43	// SD:ACMD43
#define SD_APP_GET_MID					44	// SD:ACMD44
#define SD_APP_SET_CER_RN1				45	// SD:ACMD45
#define SD_APP_SET_CER_RN2				46	// SD:ACMD46
#define SD_APP_SET_CER_RES2				47	// SD:ACMD47
#define SD_APP_SET_CER_RES1				48	// SD:ACMD48
#define SD_APP_CHANGE_SECURE_AREA		49	// SD:ACMD49
