//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitConsoles.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitConsoles.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   /*
        /// *  Fit terminal columns and rows to the dimensions of its
        /// *  DOM element.
        /// *
        /// *  Approach:
        /// *    - Rows: Truncate the division of the terminal parent element height
        /// *            by the terminal row height
        /// *
        /// *    - Columns: Truncate the division of the terminal parent element width by
        /// *               the terminal character width (apply display: inline at the
        /// *               terminal row and truncate its width with the current number
        /// *               of columns)
        /// */
        ///(function (fit) {
        ///  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string fit_js {
            get {
                return ResourceManager.GetString("fit_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /**
        /// * xterm.js: xterm, in the browser
        /// * Copyright (c) 2014, sourceLair Limited (www.sourcelair.com (MIT License)
        /// * Copyright (c) 2012-2013, Christopher Jeffrey (MIT License)
        /// * https://github.com/chjj/term.js
        /// *
        /// * Permission is hereby granted, free of charge, to any person obtaining a copy
        /// * of this software and associated documentation files (the &quot;Software&quot;), to deal
        /// * in the Software without restriction, including without limitation the rights
        /// * to use, copy, modify, merge, publish, distri [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string xterm_css {
            get {
                return ResourceManager.GetString("xterm_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!doctype html&gt;
        ///&lt;html lang=&quot;ja-jp&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///	&lt;title&gt;Terminal&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot; media=&quot;screen&quot;&gt;
        ///		#terminal {
        ///			position: absolute;
        ///			top: 0;
        ///			right: 0;
        ///			bottom: 0;
        ///			left: 0;
        ///			font-size: small;
        ///		}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div id=&quot;terminal&quot;&gt; &lt;/div&gt;
        ///	&lt;script&gt;
        ///		function start_xterm() {
        ///			var term = new Terminal({
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string xterm_html {
            get {
                return ResourceManager.GetString("xterm_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /**
        /// * xterm.js: xterm, in the browser
        /// * Copyright (c) 2014, sourceLair Limited (www.sourcelair.com (MIT License)
        /// * Copyright (c) 2012-2013, Christopher Jeffrey (MIT License)
        /// * https://github.com/chjj/term.js
        /// *
        /// * Permission is hereby granted, free of charge, to any person obtaining a copy
        /// * of this software and associated documentation files (the &quot;Software&quot;), to deal
        /// * in the Software without restriction, including without limitation the rights
        /// * to use, copy, modify, merge, publish, distri [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string xterm_js {
            get {
                return ResourceManager.GetString("xterm_js", resourceCulture);
            }
        }
    }
}
